### ISSUE TITLE
having a different urlPrefix other than /

### ISSUE THREAD

**Issue by unlucio** [jussi-kalliokoski/gulp-spa#6]
As from the doc adding the urlPrefix param

``` html
 <!-- build:js {
        "urlPrefix": "/"
    } -->
<script src="my-js-file1.js"></script>
<script src="my-js-file2.js"></script>
```

or prepending a / in front of the script path:

``` html
<script src="/my-js-file1.js"></script>
<script src="/my-js-file2.js"></script>
```

will end up having my merged file prepended by the /

``` html
<script src="/my-combined-js-file.js"></script>
```

which is fine.

what about if I want to prepend a different path?
for instance in my final result I'd like to have my script in a /scripts/ directory and my index.thml in the root (/) directory. Therefore my index.html should contain a script tag as follows:

``` html
<script src="/scripts/my-combined-js-file.js"></script>
```

Later on I'd even like to leverage on my CDN for distributing those js files and my script tags would need to be something like:

``` html
<script src="//<cdnHost>/<scriptsDir>/my-combined-js-file.js"></script>
```

I tried to achieve this as follows:

``` html
 <!-- build:js {
        "urlPrefix": "/scripts/" (or even "scripts/" and "scripts")
    } -->
<script src="my-js-file1.js"></script>
<script src="my-js-file2.js"></script>
```

or:

``` html
 <!-- build:js -->
<script src="/scripts/my-js-file1.js"></script>
<script src="/scripts/my-js-file2.js"></script>
```

but it didn't work, still giving me the same output:

``` html
<script src="/my-combined-js-file.js"></script>
```

Is gulp-spa currently able to handle this?
If I understand assignPrefix.js correctly (I'm still wrapping my mind around the lib's code) this can't happen right now.
Since I kind of really need this I'll gladly send a PR if I can get how the  "urlPrefix" thing currently works :)

cheers
lucio

**Comment by unlucio** [comment]
Ok I think I found it and I opened a PR ;P

**Comment by jussi-kalliokoski** [comment]
Hi there!

If you just want to put the files in a different directory, it's best to use [gulp-rename](https://github.com/hparra/gulp-rename), e.g.

``` javascript
gulp.src("./index.html")
  .pipe(spa.html({
    pipelines: {
      css: function (files) {
        return files.pipe(rename({ dirname: "css" }));
      },

      js: function (files) {
        return files.pipe(rename({ dirname: "js" }));
      }
    }
  }))
  .pipe(gulp.dest("./public/"));
```

This way the files are also placed in the right place on the disk, instead of the case if you fiddle with the `urlPrefix`. :)

I added a test case for that, should probably also add it to the readme.

However, your other use case of using `urlPrefix` for CDN URLs, etc., is very valid and should be supported, I'll take a look at the PR. ;)

**Comment by unlucio** [comment]
Yup, that's what I though. The code was there but it needed a couple of more key strokes to work ;P
